name: traq
description: A new Flutter project.
publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.2.0
  fpdart: ^0.3.0
  shared_preferences: ^2.0.15
  http: ^0.13.5
  flutter_animate: ^1.0.0
  flutter_svg: ^2.0.2
  uuid: ^3.0.7
  file_picker: ^5.2.2
  phosphor_flutter: ^1.4.0
  url_launcher: ^6.1.10
  smooth_page_indicator: ^1.1.0
  dotted_line: ^3.1.0
  cached_network_image: ^3.2.3
  liquid_pull_to_refresh: ^3.0.1
  carousel_slider: ^4.2.1
  pinput: ^2.2.31
  image_picker: ^0.8.7+5
  glass: ^1.0.1+1
  flutter_secure_storage: ^8.0.0
  path_provider: ^2.0.15
  substring_highlight: ^1.0.33
  local_hero: ^0.2.0
  dropdown_button2: ^1.9.2
  intl: ^0.18.0
  google_sign_in: ^5.4.2
  readmore: ^2.2.0
  timeago: ^3.3.0
  async: ^2.11.0
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  go_router: ^10.0.0
  routemaster: ^1.0.1
  responsive_builder: ^0.7.0
  google_fonts: ^4.0.4
  simple_notifier: ^1.0.2
  animate_to: ^0.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  riverpod_lint: ^1.0.1
  custom_lint:
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/
    - lib/assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
