// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOgfEubYNUBaBU1ehOTdIoCKZr-old0WI',
    appId: '1:232209430206:web:4a1dc0cf8ebbd29b2a90ef',
    messagingSenderId: '232209430206',
    projectId: 'traq-3574d',
    authDomain: 'traq-3574d.firebaseapp.com',
    storageBucket: 'traq-3574d.appspot.com',
    measurementId: 'G-87M4L96K3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9o7ysbngMVP_lq70cWn79PeJiepXMlKU',
    appId: '1:232209430206:android:80ca8746abae20932a90ef',
    messagingSenderId: '232209430206',
    projectId: 'traq-3574d',
    storageBucket: 'traq-3574d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm05mBDwXKscEZKH60Gf8V55YxMPdcaCA',
    appId: '1:232209430206:ios:a284418491a632b42a90ef',
    messagingSenderId: '232209430206',
    projectId: 'traq-3574d',
    storageBucket: 'traq-3574d.appspot.com',
    iosClientId: '232209430206-em96p54oq6jvl3hathu3skp5et3dtfrc.apps.googleusercontent.com',
    iosBundleId: 'app.kiishidart.traq',
  );
}
